from .config import VCHDDecodeConfig, vchd_config_from_dict
from .contrast import ContrastStats, compute_contrast_stats
from .decoder import visual_contrast_decode
from .history import (
    AdaptiveTemporalObservation,
    CCDHistoryObservation,
    CCDHistorySnapshot,
    CounterfactualEvidenceBatchObservation,
    CounterfactualEvidenceHistory,
    CounterfactualEvidenceObservation,
    HistoryObservation,
    SparseHistory,
    UnifiedCandidateTrajectory,
    UnifiedTrajectoryBatchObservation,
    UnifiedTrajectoryPosterior,
    compute_unified_trajectory_posterior,
    counterfactual_exposure_weights,
    history_adjusted_reliability,
    loglogistic_survival_kernel,
    observe_adaptive_temporal_history,
    observe_ccd_history,
    observe_counterfactual_evidence,
    observe_counterfactual_evidence_batch,
    observe_sparse_history,
    observe_unified_trajectory_batch,
    sparse_distribution_from_dense,
    sparse_jsd,
)
from .mmada_adapter import (
    BranchKVCache,
    MMaDAVisualAccessAdapter,
    PairedKVCache,
    PairedLogits,
    build_paired_attention_bias,
)
from .vocabulary import build_valid_text_vocab
from .window import (
    CCAWState,
    WindowPressure,
    compute_window_pressure,
    pressure_adaptive_commit_budget,
    scope_next_hard_block,
    update_ccaw_state,
    update_inverse_ccaw_state,
)

__all__ = [
    "ContrastStats",
    "CCAWState",
    "AdaptiveTemporalObservation",
    "BranchKVCache",
    "CCDHistoryObservation",
    "CCDHistorySnapshot",
    "CounterfactualEvidenceBatchObservation",
    "CounterfactualEvidenceHistory",
    "CounterfactualEvidenceObservation",
    "HistoryObservation",
    "MMaDAVisualAccessAdapter",
    "PairedKVCache",
    "PairedLogits",
    "SparseHistory",
    "UnifiedCandidateTrajectory",
    "UnifiedTrajectoryBatchObservation",
    "UnifiedTrajectoryPosterior",
    "VCHDDecodeConfig",
    "WindowPressure",
    "build_paired_attention_bias",
    "build_valid_text_vocab",
    "compute_contrast_stats",
    "compute_unified_trajectory_posterior",
    "compute_window_pressure",
    "counterfactual_exposure_weights",
    "history_adjusted_reliability",
    "loglogistic_survival_kernel",
    "observe_adaptive_temporal_history",
    "observe_ccd_history",
    "observe_counterfactual_evidence",
    "observe_counterfactual_evidence_batch",
    "observe_sparse_history",
    "observe_unified_trajectory_batch",
    "pressure_adaptive_commit_budget",
    "scope_next_hard_block",
    "sparse_distribution_from_dense",
    "sparse_jsd",
    "update_ccaw_state",
    "update_inverse_ccaw_state",
    "vchd_config_from_dict",
    "visual_contrast_decode",
]
