from .config import VCHDDecodeConfig, vchd_config_from_dict
from .contrast import ContrastStats, compute_contrast_stats
from .decoder import visual_contrast_decode
from .diagnostics import VCHDDiagnosticStep, observe_vchd_steps
from .history import (
    CounterfactualEvidenceBatchObservation,
    CounterfactualEvidenceHistory,
    CounterfactualEvidenceObservation,
    FocusDwellObservation,
    FocusFrame,
    FocusLongTailObservation,
    HistoryObservation,
    SparseHistory,
    UnifiedCandidateTrajectory,
    UnifiedTrajectoryBatchObservation,
    UnifiedTrajectoryPosterior,
    compute_focus_dwell_counter,
    compute_unified_trajectory_posterior,
    counterfactual_exposure_weights,
    focus_longtail_history_upper_bound,
    history_adjusted_reliability,
    loglogistic_survival_kernel,
    observe_counterfactual_evidence,
    observe_counterfactual_evidence_batch,
    observe_focus_dwell,
    observe_focus_longtail,
    observe_sparse_history,
    observe_unified_trajectory_batch,
    sparse_distribution_from_dense,
    sparse_jsd,
)
from .mmada_adapter import (
    BranchKVCache,
    MMaDAVisualAccessAdapter,
    PairedKVCache,
    PairedLogits,
    build_paired_attention_bias,
)
from .swd import SwdState, apply_swd_to_confidence, kl_prev_vs_curr, stability_weight
from .thinking_diffusion import (
    ThinkingSwdDecodeConfig,
    apply_psp,
    apply_vrg,
    resolve_thinking_swd_config,
    thinking_swd_config_from_dict,
)
from .vocabulary import build_valid_text_vocab
from .window import (
    CCAWState,
    WindowPressure,
    compute_window_pressure,
    pressure_adaptive_commit_budget,
    scope_next_hard_block,
    update_ccaw_state,
    update_inverse_ccaw_state,
)

__all__ = [
    "BranchKVCache",
    "CCAWState",
    "ContrastStats",
    "CounterfactualEvidenceBatchObservation",
    "CounterfactualEvidenceHistory",
    "CounterfactualEvidenceObservation",
    "FocusDwellObservation",
    "FocusFrame",
    "FocusLongTailObservation",
    "HistoryObservation",
    "MMaDAVisualAccessAdapter",
    "PairedKVCache",
    "PairedLogits",
    "SparseHistory",
    "SwdState",
    "ThinkingSwdDecodeConfig",
    "UnifiedCandidateTrajectory",
    "UnifiedTrajectoryBatchObservation",
    "UnifiedTrajectoryPosterior",
    "VCHDDecodeConfig",
    "VCHDDiagnosticStep",
    "WindowPressure",
    "apply_psp",
    "apply_swd_to_confidence",
    "apply_vrg",
    "build_paired_attention_bias",
    "build_valid_text_vocab",
    "compute_contrast_stats",
    "compute_focus_dwell_counter",
    "compute_unified_trajectory_posterior",
    "compute_window_pressure",
    "counterfactual_exposure_weights",
    "focus_longtail_history_upper_bound",
    "history_adjusted_reliability",
    "kl_prev_vs_curr",
    "loglogistic_survival_kernel",
    "observe_counterfactual_evidence",
    "observe_counterfactual_evidence_batch",
    "observe_focus_dwell",
    "observe_focus_longtail",
    "observe_sparse_history",
    "observe_unified_trajectory_batch",
    "observe_vchd_steps",
    "pressure_adaptive_commit_budget",
    "resolve_thinking_swd_config",
    "scope_next_hard_block",
    "sparse_distribution_from_dense",
    "sparse_jsd",
    "stability_weight",
    "thinking_swd_config_from_dict",
    "update_ccaw_state",
    "update_inverse_ccaw_state",
    "vchd_config_from_dict",
    "visual_contrast_decode",
]
