from .config import VCHDDecodeConfig, vchd_config_from_dict
from .contrast import ContrastStats, compute_contrast_stats
from .decoder import visual_contrast_decode
from .history import (
    HistoryObservation,
    SparseHistory,
    history_adjusted_reliability,
    observe_sparse_history,
    sparse_distribution_from_dense,
    sparse_jsd,
)
from .lavida_adapter import (
    LaViDaVisualAccessAdapter,
    MMaDAVisualAccessAdapter,
    PairedLogits,
    TokenVisualAccessAdapter,
    build_paired_attention_bias,
    build_paired_attention_bias_from_mask,
    build_paired_prefix_attention_bias,
    build_paired_shared_attention_bias_from_mask,
    infer_visual_mask_from_expanded_ids,
)
from .vcd_decoder import visual_contrastive_decode_vcd
from .vcd_noise import add_diffusion_noise, noise_images
from .thinking import (
    SwdState,
    ThinkingDecodeConfig,
    apply_psp,
    apply_swd,
    apply_vrg,
    kl_prev_vs_curr,
    resolve_thinking_config,
    response_span_token_probs,
    stability_weight,
    thinking_config_from_dict,
    visual_guided_logits,
    visual_guided_prefill,
)
from .vocabulary import build_valid_text_vocab
from .window import (
    CCAWState,
    WindowPressure,
    compute_window_pressure,
    pressure_adaptive_commit_budget,
    scope_next_hard_block,
    update_ccaw_state,
    update_inverse_ccaw_state,
)

__all__ = [
    "ContrastStats",
    "CCAWState",
    "HistoryObservation",
    "LaViDaVisualAccessAdapter",
    "MMaDAVisualAccessAdapter",
    "PairedLogits",
    "SparseHistory",
    "SwdState",
    "ThinkingDecodeConfig",
    "TokenVisualAccessAdapter",
    "VCHDDecodeConfig",
    "WindowPressure",
    "add_diffusion_noise",
    "build_paired_attention_bias",
    "build_paired_attention_bias_from_mask",
    "build_paired_prefix_attention_bias",
    "build_paired_shared_attention_bias_from_mask",
    "build_valid_text_vocab",
    "apply_psp",
    "apply_swd",
    "apply_vrg",
    "compute_contrast_stats",
    "compute_window_pressure",
    "history_adjusted_reliability",
    "infer_visual_mask_from_expanded_ids",
    "kl_prev_vs_curr",
    "noise_images",
    "observe_sparse_history",
    "pressure_adaptive_commit_budget",
    "resolve_thinking_config",
    "response_span_token_probs",
    "scope_next_hard_block",
    "sparse_distribution_from_dense",
    "sparse_jsd",
    "stability_weight",
    "thinking_config_from_dict",
    "update_ccaw_state",
    "update_inverse_ccaw_state",
    "vchd_config_from_dict",
    "visual_contrastive_decode_vcd",
    "visual_guided_logits",
    "visual_guided_prefill",
    "visual_contrast_decode",
]
